import type {
  AssessmentQuestion,
  CapabilityMasteryJourney,
  LearningDifficulty,
  LearningUnit,
} from "@/lib/learning/api-foundations-course"

export const AIF_C01_DOMAIN_ORDER = [
  "ai-ml-fundamentals",
  "genai-fundamentals",
  "foundation-models",
  "responsible-ai",
  "ai-security",
] as const

export type AifC01DomainId = (typeof AIF_C01_DOMAIN_ORDER)[number]

interface CapabilityInput {
  id: string
  domainId: AifC01DomainId
  sequence: number
  difficulty: LearningDifficulty
  title: string
  subtitle: string
  principle: string
  goal: string
  concepts: string[]
  problem: string
  mechanism: string
  decision: CapabilityMasteryJourney["decision"]
  tradeOffs: string[]
  prediction: {
    prompt: string
    preferred: [string, string]
    alternative: [string, string]
  }
  recallPrompts: string[]
  reasoning: CapabilityMasteryJourney["reasoning"]
  build: Omit<CapabilityMasteryJourney["implementation"], "language" | "steps">
  breakExercise: CapabilityMasteryJourney["breakExercise"]
  explanation: CapabilityMasteryJourney["explanation"]
  awsMap: CapabilityMasteryJourney["platformMap"]["items"]
  examLens: string
  questions: AssessmentQuestion[]
}

function capabilityUnit(input: CapabilityInput): LearningUnit {
  const masteryJourney: CapabilityMasteryJourney = {
    problem: input.problem,
    mechanism: input.mechanism,
    decision: input.decision,
    tradeOffs: input.tradeOffs,
    recallPrompts: input.recallPrompts,
    reasoning: input.reasoning,
    implementation: {
      ...input.build,
      language: "Java 21",
      steps: [
        "Run the smallest provider-neutral experiment.",
        "Capture output and one measurable observation.",
        "Write the decision and the rejected alternative.",
      ],
    },
    breakExercise: input.breakExercise,
    explanation: input.explanation,
    platformMap: {
      label: "AWS Map",
      items: input.awsMap,
      examLens: input.examLens,
    },
  }

  return {
    id: input.id,
    phase: input.sequence,
    difficulty: input.difficulty,
    title: input.title,
    subtitle: input.subtitle,
    principle: input.principle,
    goal: input.goal,
    concepts: input.concepts,
    sections: [
      { title: "Invariant mechanism", body: input.mechanism },
      { title: "Decision boundary", body: input.decision.useWhen.concat(input.decision.avoidWhen).join(" ") },
    ],
    scenario: {
      title: "Predict before learning",
      prompt: input.prediction.prompt,
      options: [
        { id: "preferred", label: input.prediction.preferred[0], consequence: input.prediction.preferred[1] },
        { id: "alternative", label: input.prediction.alternative[0], consequence: input.prediction.alternative[1] },
      ],
      trace: [
        { id: "problem", label: "Constraint", system: "Problem", detail: input.problem },
        { id: "mechanism", label: "Mechanism", system: "Capability", detail: input.mechanism },
        { id: "decision", label: "Evidence", system: "Decision", detail: input.reasoning.strongAnswerIncludes.join(" · ") },
      ],
    },
    assessment: {
      title: input.title + " exam checkpoint",
      description: "Test recall and decision transfer. Opening content or finishing a video never counts as mastery.",
      reflectionPrompt: input.explanation.prompt,
      questions: input.questions,
    },
    certification: {
      kind: "capability",
      domainId: input.domainId,
      sequence: input.sequence,
      masteryJourney,
    },
  }
}

export const aifC01CapabilityUnits: LearningUnit[] = [
  capabilityUnit({
    id: "ai-vs-ml-vs-deep-learning",
    domainId: "ai-ml-fundamentals",
    sequence: 1,
    difficulty: "Easy",
    title: "AI vs ML vs deep learning",
    subtitle: "Choose the smallest capability that solves the problem.",
    principle: "AI is the goal; ML learns patterns from data; deep learning is ML built from layered neural networks.",
    goal: "Distinguish rules, conventional ML, deep learning, and generative AI from the required outcome.",
    concepts: ["AI", "machine learning", "deep learning", "rules", "classification"],
    problem: "A support router needs exact reasons for governed decisions but also sees wording that fixed rules miss.",
    mechanism: "Rules encode decisions directly. ML estimates a mapping from examples. Deep networks learn multiple representation layers and usually require more data, compute, and controls.",
    decision: {
      useWhen: ["Use rules for explicit stable policy; use ML for repeatable patterns that rules cannot express economically."],
      avoidWhen: ["Do not choose deep learning when deterministic code completely expresses the requirement."],
      alternatives: ["Rules engine", "Search", "Human review", "Conventional statistical model"],
    },
    tradeOffs: ["Learned systems generalise but are probabilistic.", "Expressive models cost more to train, evaluate, explain, and operate."],
    prediction: {
      prompt: "Regulators require an exact reason for every denied request. What should the first implementation be?",
      preferred: ["Explicit rules plus an escalation path", "The behaviour is deterministic; unresolved cases create evidence for a later ML decision."],
      alternative: ["The largest neural model available", "Complexity and probabilistic behaviour arrive before the need is proven."],
    },
    recallPrompts: ["Define AI, ML, and deep learning without naming a vendor.", "Give one task where a rule is stronger than ML."],
    reasoning: {
      prompt: "Defend a rules, ML, or hybrid support router given 300 labelled tickets and asymmetric error costs.",
      strongAnswerIncludes: ["Data and label quality", "Error cost and escalation", "Explainability and change cost"],
    },
    build: {
      title: "Compare a rule with a learned score",
      stack: ["Plain Java"],
      objective: "Make encoded logic and learned parameters visibly different.",
      code: "record Ticket(double billing, double access) {}\nstatic String rule(Ticket t) { return t.billing() > 0.5 ? \"billing\" : \"access\"; }\nstatic String learned(Ticket t, double[] w) {\n  return t.billing() * w[0] + t.access() * w[1] >= 0 ? \"billing\" : \"access\";\n}",
      successCriteria: ["Changing a weight changes a learned prediction.", "The README states what evidence would justify ML."],
    },
    breakExercise: {
      faults: ["Swap the learned weights.", "Feed an example outside training coverage."],
      observe: ["Deterministic versus data-dependent failure", "Where abstention should begin"],
      recovery: "Add an uncertainty threshold and route ambiguous cases to a human.",
    },
    explanation: {
      prompt: "Explain the hierarchy and justify the smallest suitable approach to a product owner.",
      evidenceCriteria: ["Correct hierarchy", "Problem-to-technique mapping", "One rejected alternative"],
    },
    awsMap: [
      { invariant: "Managed access to pretrained generative models", implementation: "Amazon Bedrock", why: "Use when the task benefits from a foundation model without owning base-model infrastructure." },
      { invariant: "Build and host custom ML", implementation: "Amazon SageMaker AI", why: "Use when the organisation owns the model lifecycle." },
    ],
    examLens: "Identify the output and constraints first; a service name does not turn a deterministic policy into ML.",
    questions: [
      {
        id: "aif-ai-ml-hierarchy",
        prompt: "Which relationship is correct?",
        options: ["Deep learning is ML, and ML is one approach to AI", "AI is only deep learning", "ML is a database", "Deep learning is rule-only"],
        correctAnswer: "Deep learning is ML, and ML is one approach to AI",
        explanation: "The terms form a scope hierarchy.",
        reviewLabel: "AI/ML hierarchy",
      },
      {
        id: "aif-ai-ml-choice",
        prompt: "When is a rule usually preferable?",
        options: ["Policy is deterministic and exactly explainable", "Input is high-dimensional audio", "Millions of labels exist", "Semantic generation is required"],
        correctAnswer: "Policy is deterministic and exactly explainable",
        explanation: "A complete explicit rule is simpler and more auditable.",
        reviewLabel: "Technique choice",
      },
    ],
  }),
  capabilityUnit({
    id: "training-vs-inference",
    domainId: "ai-ml-fundamentals",
    sequence: 2,
    difficulty: "Easy",
    title: "Training vs inference",
    subtitle: "Separate learning parameters from using frozen parameters.",
    principle: "Training estimates parameters from evidence; inference applies an approved model version to new input.",
    goal: "Trace data, parameters, versions, evaluation, deployment, and production predictions.",
    concepts: ["training", "inference", "validation", "model version", "drift"],
    problem: "A classifier succeeds in a notebook but fails after release because test data, training, and live behaviour were mixed.",
    mechanism: "Training updates parameters to reduce an objective. Validation estimates generalisation. Inference loads a fixed approved version and produces outputs without relearning from each request.",
    decision: {
      useWhen: ["Train only when an existing model cannot satisfy the measured task; serve immutable approved versions."],
      avoidWhen: ["Do not train on test cases or silently update parameters inside production requests."],
      alternatives: ["Pretrained model", "Prompting", "RAG", "Rules"],
    },
    tradeOffs: ["Training adds data, compute, reproducibility, and governance cost.", "Batch inference trades freshness for cost; online inference adds latency and availability concerns."],
    prediction: {
      prompt: "Should one production ticket update the classifier before returning its prediction?",
      preferred: ["Use the frozen approved model", "The request is reproducible; new evidence enters a controlled retraining cycle."],
      alternative: ["Retrain inside every request", "Outputs become unreviewed and non-reproducible."],
    },
    recallPrompts: ["What changes during training?", "What stays stable during one governed inference request?"],
    reasoning: {
      prompt: "Choose batch or real-time inference for nightly learner recommendations.",
      strongAnswerIncludes: ["Freshness requirement", "Latency and cost", "Versioned rollback"],
    },
    build: {
      title: "Freeze and version a tiny classifier",
      stack: ["Plain Java", "JSON artifact"],
      objective: "Prove inference is repeatable for an input and model version.",
      code: "record Model(String version, double bias, double weight) {\n  double infer(double x) { return 1.0 / (1.0 + Math.exp(-(bias + weight * x))); }\n}\nvar model = new Model(\"router-7\", -0.4, 1.7);\nSystem.out.println(model.version() + \":\" + model.infer(0.8));",
      successCriteria: ["Repeated inputs produce the same score.", "Every output carries the model version."],
    },
    breakExercise: {
      faults: ["Mutate weights between requests.", "Deploy without recording a version."],
      observe: ["Loss of reproducibility", "Missing rollback evidence"],
      recovery: "Make artifacts immutable and promote versions only after evaluation.",
    },
    explanation: {
      prompt: "Trace one example from training data through approval and production inference.",
      evidenceCriteria: ["Data split", "Parameter boundary", "Version and rollback"],
    },
    awsMap: [
      { invariant: "Managed training and hosted inference", implementation: "SageMaker training jobs and endpoints", why: "They separate training from serving choices." },
      { invariant: "Managed foundation-model inference", implementation: "Amazon Bedrock", why: "Applications invoke selected models without owning base-model training." },
    ],
    examLens: "Separate build-time learning from run-time prediction and choose inference mode from workload constraints.",
    questions: [
      {
        id: "aif-training-change",
        prompt: "What primarily changes during training?",
        options: ["Model parameters", "TLS semantics", "DNS records per request", "IAM usernames"],
        correctAnswer: "Model parameters",
        explanation: "Training updates parameters from examples.",
        reviewLabel: "Training",
      },
      {
        id: "aif-inference-version",
        prompt: "Why record a model version with output?",
        options: ["Reproduction, audit, and rollback", "Guaranteed correctness", "No drift", "Replacement for authorization"],
        correctAnswer: "Reproduction, audit, and rollback",
        explanation: "Version evidence identifies the artifact that served the request.",
        reviewLabel: "Inference governance",
      },
    ],
  }),
  capabilityUnit({
    id: "foundation-models",
    domainId: "genai-fundamentals",
    sequence: 3,
    difficulty: "Easy",
    title: "Foundation models",
    subtitle: "Start broad, then constrain and evaluate for a task.",
    principle: "A foundation model is broadly pretrained for many downstream tasks; it is a component, not a complete product.",
    goal: "Explain pretraining, adaptation, model selection, and capability boundaries.",
    concepts: ["foundation model", "pretraining", "adaptation", "model selection"],
    problem: "A team needs summarisation and question answering but cannot train a large language model from scratch.",
    mechanism: "Broad pretraining learns reusable representations. An application selects a model, supplies instructions and context, evaluates outputs, and adds controls around probabilistic generation.",
    decision: {
      useWhen: ["Use a foundation model for broad language or multimodal capability; select the smallest model meeting measured requirements."],
      avoidWhen: ["Do not use one for exact policy code or assume it contains current private facts."],
      alternatives: ["Rules", "Task-specific ML", "Search", "Smaller local model"],
    },
    tradeOffs: ["Larger models may improve capability while raising cost and latency.", "Open models increase control and transfer hosting responsibility."],
    prediction: {
      prompt: "A small local model meets quality at one tenth of the latency. What should the design start with?",
      preferred: ["Use the smaller measured model", "It meets the workload requirement with a smaller operating envelope."],
      alternative: ["Use the largest model by default", "Model size substitutes for workload evidence."],
    },
    recallPrompts: ["What makes a model foundational?", "Why is it not a complete application?"],
    reasoning: {
      prompt: "Compare managed and self-hosted models for private learner data.",
      strongAnswerIncludes: ["Quality and latency", "Data boundary", "Hosting skill and total cost"],
    },
    build: {
      title: "Call a local open model",
      stack: ["Java HttpClient", "llama.cpp-compatible local endpoint"],
      objective: "Measure a model without an AWS dependency.",
      code: "var request = HttpRequest.newBuilder(URI.create(\"http://localhost:8080/completion\"))\n    .header(\"Content-Type\", \"application/json\")\n    .POST(HttpRequest.BodyPublishers.ofString(\"{\\\"prompt\\\":\\\"Explain TLS\\\"}\"))\n    .build();\nvar response = HttpClient.newHttpClient().send(request, HttpResponse.BodyHandlers.ofString());",
      successCriteria: ["No AWS credential is required.", "Latency and output quality are recorded."],
    },
    breakExercise: {
      faults: ["Stop the local model.", "Change model version without evaluation."],
      observe: ["Timeout behaviour", "Quality regression"],
      recovery: "Bound requests with timeouts, pin versions, and block promotion on regression.",
    },
    explanation: {
      prompt: "Explain why broad pretraining still needs context, evaluation, and controls.",
      evidenceCriteria: ["Pretraining versus use", "Measured selection", "Application responsibility"],
    },
    awsMap: [
      { invariant: "Managed access to multiple foundation models", implementation: "Amazon Bedrock", why: "Invoke supported models without managing base infrastructure." },
      { invariant: "Custom model lifecycle", implementation: "Amazon SageMaker AI", why: "Own more training, hosting, and operations." },
    ],
    examLens: "Choose from modality, quality, latency, cost, context, and governance—not prestige.",
    questions: [
      {
        id: "aif-fm-definition",
        prompt: "What distinguishes a foundation model?",
        options: ["Broad pretraining for many downstream tasks", "A fixed rule table", "Guaranteed factuality", "AWS dependency"],
        correctAnswer: "Broad pretraining for many downstream tasks",
        explanation: "Foundation models learn reusable capability before task adaptation.",
        reviewLabel: "Foundation models",
      },
      {
        id: "aif-fm-selection",
        prompt: "What is the strongest selection basis?",
        options: ["Representative quality, latency, cost, and governance evidence", "Largest size", "Logo colour", "Assumed private knowledge"],
        correctAnswer: "Representative quality, latency, cost, and governance evidence",
        explanation: "Selection is a measured workload decision.",
        reviewLabel: "Model selection",
      },
    ],
  }),
  capabilityUnit({
    id: "transformers",
    domainId: "genai-fundamentals",
    sequence: 4,
    difficulty: "Medium",
    title: "Transformers",
    subtitle: "Model relationships among tokens with attention.",
    principle: "Attention lets each token combine information from other relevant tokens.",
    goal: "Explain self-attention, positional information, and context limitations.",
    concepts: ["transformer", "attention", "query", "key", "value", "position"],
    problem: "A model must connect a pronoun to a noun many tokens earlier.",
    mechanism: "Tokens produce query, key, and value representations. Query-key similarity yields weights over values; positional information preserves order. Repeated layers learn richer relationships.",
    decision: {
      useWhen: ["Use transformer models for sequence tasks needing contextual relationships."],
      avoidWhen: ["Do not use them for simple exact parsing or equate attention with verified reasoning."],
      alternatives: ["Parsers", "Recurrent models", "Search"],
    },
    tradeOffs: ["Standard attention grows expensive with sequence length.", "Long context raises compute without guaranteeing use of every fact."],
    prediction: {
      prompt: "Which mechanism connects a pronoun with a distant noun?",
      preferred: ["Attention over token representations", "The model can weight the earlier token as relevant."],
      alternative: ["DNS resolution", "DNS maps network names, not language relationships."],
    },
    recallPrompts: ["What do query, key, and value do?", "Why is positional information needed?"],
    reasoning: {
      prompt: "Evaluate doubling context length for every request.",
      strongAnswerIncludes: ["Need for distant context", "Compute and latency", "Retrieval alternative"],
    },
    build: {
      title: "Calculate attention weights",
      stack: ["Plain Java"],
      objective: "Make query-key weighting concrete.",
      code: "static double[] softmax(double[] s) {\n  double max = Arrays.stream(s).max().orElseThrow();\n  double[] e = Arrays.stream(s).map(v -> Math.exp(v - max)).toArray();\n  double sum = Arrays.stream(e).sum();\n  return Arrays.stream(e).map(v -> v / sum).toArray();\n}",
      successCriteria: ["Weights sum to one.", "A larger score contributes more to the result."],
    },
    breakExercise: {
      faults: ["Remove position signals.", "Increase context sharply."],
      observe: ["Order ambiguity", "Memory and latency growth"],
      recovery: "Use the smallest sufficient context and evaluate retrieval or summarisation.",
    },
    explanation: {
      prompt: "Explain attention without claiming it proves factuality or human reasoning.",
      evidenceCriteria: ["Query-key-value", "Position", "One limitation"],
    },
    awsMap: [
      { invariant: "Invoke transformer-based models", implementation: "Amazon Bedrock", why: "The service packages inference; attention remains a model mechanism." },
      { invariant: "Train or host custom transformers", implementation: "Amazon SageMaker AI", why: "Use when owning the custom model lifecycle." },
    ],
    examLens: "Understand the mechanism and its limits independently of the managed service.",
    questions: [
      {
        id: "aif-transformer-attention",
        prompt: "What does self-attention do?",
        options: ["Weights relationships among token representations", "Encrypts traffic", "Creates IAM policy", "Stores vectors"],
        correctAnswer: "Weights relationships among token representations",
        explanation: "Attention combines information by learned relevance.",
        reviewLabel: "Attention",
      },
      {
        id: "aif-transformer-position",
        prompt: "Why is positional information needed?",
        options: ["Attention alone does not encode order", "It grants permissions", "It guarantees citations", "It replaces tokens"],
        correctAnswer: "Attention alone does not encode order",
        explanation: "Position distinguishes reordered token sets.",
        reviewLabel: "Position",
      },
    ],
  }),
  capabilityUnit({
    id: "tokens",
    domainId: "genai-fundamentals",
    sequence: 5,
    difficulty: "Easy",
    title: "Tokens",
    subtitle: "Budget the units a model actually processes.",
    principle: "Models process token IDs, not human word counts; inputs and outputs share a finite context.",
    goal: "Explain tokenisation, context, truncation, latency, and usage.",
    concepts: ["token", "tokeniser", "context window", "truncation"],
    problem: "Instructions, history, sources, and requested output exceed the context even though each looks short.",
    mechanism: "A model-specific tokeniser maps input to vocabulary IDs. Language, symbols, and code split differently, and all prompt regions plus generated output share the limit.",
    decision: {
      useWhen: ["Count with the selected model tokeniser and reserve output capacity."],
      avoidWhen: ["Do not assume one token equals one word or truncate authoritative evidence silently."],
      alternatives: ["Chunking", "Retrieval", "Summarisation", "Shorter history"],
    },
    tradeOffs: ["More context costs latency and money.", "Truncation can remove decisive evidence; summaries can lose detail."],
    prediction: {
      prompt: "The context is full before generation. What should happen?",
      preferred: ["Retrieve relevant chunks and reserve output space", "The request preserves high-value evidence within the limit."],
      alternative: ["Append every document", "The request may fail or truncate the wrong material."],
    },
    recallPrompts: ["Why is a token not always a word?", "What shares a context window?"],
    reasoning: {
      prompt: "Allocate a context budget across instructions, history, evidence, and answer.",
      strongAnswerIncludes: ["Explicit allocation", "Overflow policy", "Quality test after trimming"],
    },
    build: {
      title: "Add a conservative budget guard",
      stack: ["Plain Java", "Real model tokeniser in production"],
      objective: "Reject oversized requests before invocation.",
      code: "static int teachingEstimate(String text) {\n  return (int) Math.ceil(text.codePointCount(0, text.length()) / 3.0);\n}\nstatic void requireBudget(String prompt, int max) {\n  if (teachingEstimate(prompt) > max) throw new IllegalArgumentException(\"over budget\");\n}",
      successCriteria: ["The estimate is labelled non-authoritative.", "Output capacity is reserved."],
    },
    breakExercise: {
      faults: ["Use emoji-heavy input.", "Set output reserve to zero."],
      observe: ["Estimate drift", "Truncated output"],
      recovery: "Use the exact tokeniser and test representative languages and code.",
    },
    explanation: {
      prompt: "Explain context as a budget, not a promise the model uses every fact.",
      evidenceCriteria: ["Token variability", "Shared limit", "Overflow policy"],
    },
    awsMap: [
      { invariant: "Model-specific token limits and usage", implementation: "Amazon Bedrock model inference", why: "Applications still own context and usage controls." },
      { invariant: "Select relevant context", implementation: "Knowledge Bases for Amazon Bedrock", why: "Retrieval avoids appending every document." },
    ],
    examLens: "Relate tokens to context, latency, and cost using model-specific limits.",
    questions: [
      {
        id: "aif-token-definition",
        prompt: "What is a token?",
        options: ["A model-specific processed unit", "Exactly one word", "An access key", "A transaction"],
        correctAnswer: "A model-specific processed unit",
        explanation: "Tokenisers use model vocabularies, not universal word boundaries.",
        reviewLabel: "Tokens",
      },
      {
        id: "aif-context-budget",
        prompt: "Why reserve output capacity?",
        options: ["Input and output share finite context", "TLS requires it", "Embeddings fail otherwise", "IAM blocks output"],
        correctAnswer: "Input and output share finite context",
        explanation: "An input-only budget can leave no room for generation.",
        reviewLabel: "Context",
      },
    ],
  }),
  capabilityUnit({
    id: "embeddings",
    domainId: "genai-fundamentals",
    sequence: 6,
    difficulty: "Medium",
    title: "Embeddings",
    subtitle: "Represent meaning as vectors.",
    principle: "An embedding maps input to a vector whose learned geometry supports a similarity task.",
    goal: "Explain generation, dimensions, semantic neighbourhoods, and model-version consistency.",
    concepts: ["embedding", "vector", "dimension", "normalisation"],
    problem: "Keyword search misses that 'mutual certificate authentication' relates to 'mTLS'.",
    mechanism: "An embedding model maps items to fixed-length vectors and places related examples closer. Queries and documents must share a compatible model and preprocessing path.",
    decision: {
      useWhen: ["Use embeddings for semantic retrieval, clustering, recommendations, or deduplication."],
      avoidWhen: ["Do not use them for exact identifiers or compare incompatible vector spaces."],
      alternatives: ["Keyword search", "Structured filters", "Hybrid search"],
    },
    tradeOffs: ["Semantic recall can reduce exactness.", "Dimensions add storage and compute; embeddings can encode bias."],
    prediction: {
      prompt: "How can a search retrieve an mTLS note without exact wording?",
      preferred: ["Compare compatible query and note embeddings", "Semantic geometry can surface related phrasing."],
      alternative: ["Require exact equality", "The relevant note is missed."],
    },
    recallPrompts: ["What is an embedding?", "Why must vector spaces be compatible?"],
    reasoning: {
      prompt: "Choose semantic, keyword, or hybrid search for docs with exact control IDs.",
      strongAnswerIncludes: ["Semantic recall", "Exact precision", "Filters and hybrid ranking"],
    },
    build: {
      title: "Normalise teaching vectors",
      stack: ["Plain Java"],
      objective: "Treat vector dimensions and versions as explicit data.",
      code: "static double[] normalise(double[] v) {\n  double n = Math.sqrt(Arrays.stream(v).map(x -> x * x).sum());\n  if (n == 0) throw new IllegalArgumentException(\"zero vector\");\n  return Arrays.stream(v).map(x -> x / n).toArray();\n}",
      successCriteria: ["Normalised length is approximately one.", "Model version is stored with the index."],
    },
    breakExercise: {
      faults: ["Mix dimensions.", "Re-embed half the corpus with a new model."],
      observe: ["Runtime rejection", "Meaningless cross-space scores"],
      recovery: "Version preprocessing and rebuild indexes atomically.",
    },
    explanation: {
      prompt: "Explain embeddings without claiming each dimension has a simple human label.",
      evidenceCriteria: ["Vector mapping", "Compatibility", "Evaluation"],
    },
    awsMap: [
      { invariant: "Generate semantic vectors", implementation: "Embedding models through Amazon Bedrock", why: "The model produces vectors while the app owns compatibility." },
      { invariant: "Index vectors", implementation: "Amazon OpenSearch Service", why: "Vector indexes support filtered nearest-neighbour retrieval." },
    ],
    examLens: "Distinguish embedding generation from storage and similarity search.",
    questions: [
      {
        id: "aif-embedding-purpose",
        prompt: "What is a common embedding purpose?",
        options: ["Represent semantic relationships", "Encrypt parameters", "Replace all filters", "Create accounts"],
        correctAnswer: "Represent semantic relationships",
        explanation: "Embeddings provide numeric geometry for similarity.",
        reviewLabel: "Embeddings",
      },
      {
        id: "aif-embedding-compatibility",
        prompt: "Why use compatible models for query and documents?",
        options: ["Coordinates must share a learned space", "It removes bias", "It removes storage", "TLS requires it"],
        correctAnswer: "Coordinates must share a learned space",
        explanation: "Unrelated spaces do not preserve intended geometry.",
        reviewLabel: "Compatibility",
      },
    ],
  }),
  capabilityUnit({
    id: "vector-similarity",
    domainId: "genai-fundamentals",
    sequence: 7,
    difficulty: "Medium",
    title: "Vector similarity",
    subtitle: "Rank by geometry, then validate relevance.",
    principle: "Similarity is a ranking signal, not proof of equivalence, truth, or authorization.",
    goal: "Calculate cosine similarity and reason about top-k, thresholds, filters, and approximate search.",
    concepts: ["cosine similarity", "dot product", "top-k", "threshold"],
    problem: "A vector index must choose a small relevant set from thousands of notes.",
    mechanism: "Cosine compares vector direction. An index retrieves high-scoring candidates, often approximately, before metadata filters or reranking.",
    decision: {
      useWhen: ["Use similarity to rank semantic candidates and tune on labelled queries."],
      avoidWhen: ["Do not use it for authorization, exact IDs, or factual verification."],
      alternatives: ["Exact lookup", "Keyword ranking", "Filters", "Reranking"],
    },
    tradeOffs: ["Higher top-k improves recall and adds noise.", "Approximate indexes exchange exactness for speed."],
    prediction: {
      prompt: "The top match belongs to another tenant. Should its score allow access?",
      preferred: ["Apply authorization filters", "Only allowed candidates may be ranked or used."],
      alternative: ["Treat similarity as authorization", "Semantic closeness leaks data."],
    },
    recallPrompts: ["What does cosine compare?", "How do top-k and thresholds differ?"],
    reasoning: {
      prompt: "Repair high-recall but low-precision retrieval.",
      strongAnswerIncludes: ["Measured precision/recall", "Filters", "Top-k or reranking trade-off"],
    },
    build: {
      title: "Rank with cosine similarity",
      stack: ["Plain Java"],
      objective: "Create an exact baseline before adding a vector database.",
      code: "static double cosine(double[] a, double[] b) {\n  if (a.length != b.length) throw new IllegalArgumentException(\"dimension\");\n  double dot=0, aa=0, bb=0;\n  for (int i=0;i<a.length;i++){ dot+=a[i]*b[i]; aa+=a[i]*a[i]; bb+=b[i]*b[i]; }\n  if (aa==0 || bb==0) throw new IllegalArgumentException(\"zero\");\n  return dot/(Math.sqrt(aa)*Math.sqrt(bb));\n}",
      successCriteria: ["Identical directions score near one.", "Invalid dimensions fail."],
    },
    breakExercise: {
      faults: ["Set top-k to the corpus size.", "Disable tenant filters."],
      observe: ["Context growth", "Cross-tenant leakage"],
      recovery: "Separate access filtering from ranking and tune on labelled queries.",
    },
    explanation: {
      prompt: "Explain why nearest does not mean correct, authorized, or sufficient.",
      evidenceCriteria: ["Metric", "Ranking versus truth", "Filters"],
    },
    awsMap: [
      { invariant: "Vector search", implementation: "Amazon OpenSearch Service", why: "Index vectors and filter candidates at scale." },
      { invariant: "Managed retrieval orchestration", implementation: "Knowledge Bases for Amazon Bedrock", why: "Connect sources, embeddings, storage, and retrieval." },
    ],
    examLens: "Keep embeddings, stores, metrics, retrieval, and authorization distinct.",
    questions: [
      {
        id: "aif-vector-cosine",
        prompt: "What does cosine similarity compare?",
        options: ["Vector angle", "IAM length", "Certificate age", "Transaction count"],
        correctAnswer: "Vector angle",
        explanation: "Cosine compares direction while accounting for magnitude.",
        reviewLabel: "Cosine",
      },
      {
        id: "aif-vector-auth",
        prompt: "Can similarity replace authorization?",
        options: ["No, relevance and access are separate", "Yes above 0.9", "Yes for embeddings", "Yes at top-k one"],
        correctAnswer: "No, relevance and access are separate",
        explanation: "A score says nothing about caller permission.",
        reviewLabel: "Boundaries",
      },
    ],
  }),
  capabilityUnit({
    id: "hallucination",
    domainId: "genai-fundamentals",
    sequence: 8,
    difficulty: "Medium",
    title: "Hallucination",
    subtitle: "Detect unsupported claims and design abstention.",
    principle: "Fluent generation predicts plausible text; factual support requires evidence and verification outside the model.",
    goal: "Apply grounding, citation checks, evaluation, abstention, and human escalation.",
    concepts: ["hallucination", "grounding", "citation", "abstention"],
    problem: "A course assistant invents a refund rule with confident wording.",
    mechanism: "The model predicts likely tokens from context and parameters. Grounding supplies evidence; claim checks, citations, thresholds, and escalation constrain unsupported output.",
    decision: {
      useWhen: ["Ground claims that depend on current or private sources."],
      avoidWhen: ["Do not let generated text execute authoritative transactions or equate low temperature with truth."],
      alternatives: ["Exact lookup", "Extractive answer", "Search", "Human response"],
    },
    tradeOffs: ["Abstention lowers harmful claims and answer coverage.", "Grounding inherits retrieval failures."],
    prediction: {
      prompt: "No approved source supports the requested policy. What should happen?",
      preferred: ["Abstain and escalate", "A safe no-answer preserves trust."],
      alternative: ["Generate the likely policy", "Fluency masks an unsupported claim."],
    },
    recallPrompts: ["Define hallucination.", "Name three impact controls."],
    reasoning: {
      prompt: "Contrast controls for creative brainstorming and a regulated policy assistant.",
      strongAnswerIncludes: ["Different error costs", "Grounding", "Abstention and human review"],
    },
    build: {
      title: "Require supported citation IDs",
      stack: ["Plain Java"],
      objective: "Reject answers whose citations are absent from retrieved evidence.",
      code: "record Answer(String text, Set<String> citations) {}\nstatic Answer requireGrounding(Answer a, Set<String> retrieved) {\n  return a.citations().isEmpty() || !retrieved.containsAll(a.citations())\n      ? new Answer(\"No approved evidence is available.\", Set.of()) : a;\n}",
      successCriteria: ["Unsupported citations trigger abstention.", "Plausible false answers are in tests."],
    },
    breakExercise: {
      faults: ["Use a real source ID for an unsupported claim.", "Retrieve the wrong document."],
      observe: ["Citation is not entailment", "Retrieval error propagation"],
      recovery: "Evaluate retrieval and claim support separately; escalate high-impact uncertainty.",
    },
    explanation: {
      prompt: "Explain why grounding reduces hallucination without guaranteeing truth.",
      evidenceCriteria: ["Probabilistic generation", "Retrieval failure", "Verification"],
    },
    awsMap: [
      { invariant: "Ground output in enterprise sources", implementation: "Knowledge Bases for Amazon Bedrock", why: "Retrieved context can make answers traceable." },
      { invariant: "Evaluate and constrain behaviour", implementation: "Amazon Bedrock model evaluation and Guardrails", why: "Measure behaviour and enforce configured policies." },
    ],
    examLens: "Select grounding, evaluation, and oversight from the consequence of an unsupported answer.",
    questions: [
      {
        id: "aif-hallucination-definition",
        prompt: "What is hallucination?",
        options: ["Plausible unsupported or incorrect content", "A timeout", "An encrypted prompt", "A vector dimension"],
        correctAnswer: "Plausible unsupported or incorrect content",
        explanation: "Fluency can hide missing support.",
        reviewLabel: "Hallucination",
      },
      {
        id: "aif-hallucination-control",
        prompt: "What should a high-impact assistant do without evidence?",
        options: ["Abstain or escalate", "Invent", "Raise temperature", "Disable logs"],
        correctAnswer: "Abstain or escalate",
        explanation: "No-answer is safer than an unsupported authoritative claim.",
        reviewLabel: "Safe response",
      },
    ],
  }),
  capabilityUnit({
    id: "prompt-engineering",
    domainId: "foundation-models",
    sequence: 9,
    difficulty: "Medium",
    title: "Prompt engineering",
    subtitle: "Express task, context, constraints, and output contracts explicitly.",
    principle: "A prompt is a contract for probabilistic behaviour; clarity helps, but evaluation proves it.",
    goal: "Design trusted instructions, delimiters, examples, structured output, and injection boundaries.",
    concepts: ["system instruction", "few-shot", "schema", "prompt injection"],
    problem: "A model returns inconsistent JSON and follows instructions embedded in untrusted notes.",
    mechanism: "Prompts assemble trusted policy, user intent, untrusted context, examples, and an output contract. Validation and permissions handle non-compliance outside the model.",
    decision: { useWhen: ["Use prompts for task framing, format, tone, and lightweight behaviour; version them like code."], avoidWhen: ["Do not put secrets in prompts or rely on wording as the only security control."], alternatives: ["Deterministic code", "Tool calling", "RAG", "Fine-tuning"] },
    tradeOffs: ["Long prompts raise clarity and token cost.", "Examples can anchor and bias behaviour."],
    prediction: { prompt: "The API requires stable JSON. Which design is strongest?", preferred: ["Specify a schema, validate, and handle failure", "The model gets a contract and code protects the boundary."], alternative: ["Ask for good JSON and trust it", "Malformed output reaches downstream code."] },
    recallPrompts: ["Name trusted and untrusted prompt regions.", "Why does an example not guarantee compliance?"],
    reasoning: { prompt: "A retrieved document says to ignore system policy. Design the control layers.", strongAnswerIncludes: ["Treat context as data", "Least-privilege tools", "Validation and adversarial tests"] },
    build: { title: "Create a versioned Java prompt", stack: ["Plain Java", "JSON schema validator optional"], objective: "Keep instructions, untrusted context, and output visibly separate.", code: "record PromptInput(String question, String context) {}\nstatic String build(PromptInput i) {\n  return \"SYSTEM: Answer only from CONTEXT. Return {answer,citations}.\\n\"\n      + \"CONTEXT_START\\n\" + i.context() + \"\\nCONTEXT_END\\n\"\n      + \"USER: \" + i.question();\n}", successCriteria: ["Prompt version is recorded.", "Malformed output is rejected."] },
    breakExercise: { faults: ["Insert an instruction into context.", "Remove the schema."], observe: ["Injection susceptibility", "Format failure"], recovery: "Keep policy outside untrusted data, validate output, restrict tools, and add adversarial tests." },
    explanation: { prompt: "Explain prompt engineering as contract design and where it stops being security.", evidenceCriteria: ["Prompt regions", "Validation", "One alternative"] },
    awsMap: [{ invariant: "Invoke with instructions and context", implementation: "Amazon Bedrock model inference", why: "Applications supply versioned prompts." }, { invariant: "Apply policy outside wording", implementation: "Guardrails for Amazon Bedrock", why: "Configured controls complement prompts." }],
    examLens: "Distinguish zero-shot, few-shot, structured output, and security boundaries.",
    questions: [
      { id: "aif-prompt-structure", prompt: "What most improves reliable structured output?", options: ["Explicit schema plus validation", "A vague request", "Secrets in prompt", "No constraints"], correctAnswer: "Explicit schema plus validation", explanation: "Prompting guides; validation protects consumers.", reviewLabel: "Prompt contracts" },
      { id: "aif-prompt-security", prompt: "Why is a system prompt not complete security?", options: ["Deterministic tool, data, and output controls remain required", "Prompts are DNS", "TLS cannot carry prompts", "Models cannot read"], correctAnswer: "Deterministic tool, data, and output controls remain required", explanation: "Security is enforced outside probabilistic text.", reviewLabel: "Prompt injection" },
    ],
  }),
  capabilityUnit({
    id: "rag",
    domainId: "foundation-models",
    sequence: 10,
    difficulty: "Hard",
    title: "Retrieval-augmented generation (RAG)",
    subtitle: "Retrieve current evidence before generation.",
    principle: "RAG changes model context at inference; it neither retrains the model nor guarantees evidence.",
    goal: "Trace ingestion, chunking, embedding, retrieval, prompting, citation, and evaluation.",
    concepts: ["RAG", "chunking", "retrieval", "grounding", "reranking"],
    problem: "An AWS tutor must answer from notes that change daily and cite an approved section.",
    mechanism: "Documents are chunked, embedded, and indexed. Queries retrieve authorised candidates, optionally rerank them, and place evidence into the prompt before claim checks.",
    decision: { useWhen: ["Use RAG for changing, private, or source-citable knowledge."], avoidWhen: ["Do not use it when an exact transactional API owns the answer."], alternatives: ["Search-only", "Tool call", "Long context", "Fine-tuning for behaviour"] },
    tradeOffs: ["Small chunks improve precision and can lose context.", "Large top-k improves recall and adds noise, latency, and tokens."],
    prediction: { prompt: "The source changes daily. Fine-tune after every edit?", preferred: ["Update the retrieval index", "Current evidence enters without daily parameter changes."], alternative: ["Retrain after every edit", "Parameters become stale content storage."] },
    recallPrompts: ["List the RAG pipeline.", "Where can it fail before generation?"],
    reasoning: { prompt: "A fluent answer cites another tenant's document. Find controls.", strongAnswerIncludes: ["Tenant filtering", "Retrieval quality", "Claim-to-source validation"] },
    build: { title: "Build in-memory Java retrieval", stack: ["Plain Java", "Local embedding adapter"], objective: "Filter, rank, and cite before adding a managed store.", code: "record Chunk(String id, String tenant, String text, double[] vector) {}\nstatic List<Chunk> retrieve(List<Chunk> chunks, String tenant, double[] q, int k) {\n  return chunks.stream().filter(c -> c.tenant().equals(tenant))\n      .sorted(Comparator.comparingDouble((Chunk c) -> cosine(q, c.vector())).reversed())\n      .limit(k).toList();\n}", successCriteria: ["Only authorised chunks return.", "Every answer carries source IDs."] },
    breakExercise: { faults: ["Split a critical sentence.", "Remove tenant filter.", "Index stale versions."], observe: ["Lost context", "Data leakage", "Outdated answers"], recovery: "Version sources, test chunking, authorize before retrieval, and support abstention." },
    explanation: { prompt: "Explain how RAG differs from fine-tuning and why both need evaluation.", evidenceCriteria: ["Inference-time context", "Failure path", "Freshness and citations"] },
    awsMap: [{ invariant: "Managed ingestion and retrieval", implementation: "Knowledge Bases for Amazon Bedrock", why: "Orchestrate supported sources, embeddings, stores, and retrieval." }, { invariant: "Source and vector storage", implementation: "Amazon S3 and Amazon OpenSearch Service", why: "Source ownership and index design remain explicit." }],
    examLens: "Choose RAG for current knowledge and fine-tuning for learned behaviour.",
    questions: [
      { id: "aif-rag-purpose", prompt: "What is RAG's primary purpose?", options: ["Provide external context at inference", "Update parameters per request", "Replace authorization", "Guarantee truth"], correctAnswer: "Provide external context at inference", explanation: "RAG retrieves evidence into context.", reviewLabel: "RAG" },
      { id: "aif-rag-security", prompt: "Where should tenant authorization occur?", options: ["Before or during retrieval", "Only in prose", "Through similarity", "Nowhere with citations"], correctAnswer: "Before or during retrieval", explanation: "Unauthorised chunks must not enter context.", reviewLabel: "Secure retrieval" },
    ],
  }),
  capabilityUnit({
    id: "fine-tuning",
    domainId: "foundation-models",
    sequence: 11,
    difficulty: "Hard",
    title: "Fine-tuning",
    subtitle: "Adapt behaviour with curated examples.",
    principle: "Fine-tuning changes parameters to make target behaviour likely; it is not a live knowledge database.",
    goal: "Choose adaptation only after prompts and retrieval are measured.",
    concepts: ["fine-tuning", "examples", "LoRA", "overfitting"],
    problem: "A model knows the facts but uses the wrong labels and tone despite tested prompts.",
    mechanism: "Input-output examples update all or some weights. The adapted artifact is versioned and compared with the base model for quality, safety, and retained capability.",
    decision: { useWhen: ["Use for repeated style, terminology, format, or task behaviour with enough quality examples."], avoidWhen: ["Do not use for changing facts or train on secrets and test cases."], alternatives: ["Prompting", "Few-shot", "RAG", "Post-processing"] },
    tradeOffs: ["Adaptation can improve consistency and reduce generality.", "Training adds governance and compute cost."],
    prediction: { prompt: "A policy changes weekly. Fine-tune first?", preferred: ["No—retrieve the current policy", "Knowledge stays linked to its source."], alternative: ["Retrain every edit", "Parameters become stale content storage."] },
    recallPrompts: ["What changes in fine-tuning?", "Why compare base and adapted models?"],
    reasoning: { prompt: "Fine-tuning improves JSON but worsens safety. Decide whether to ship.", strongAnswerIncludes: ["Independent gates", "Rollback", "Validation alternative"] },
    build: { title: "Validate a Java adaptation dataset", stack: ["Plain Java", "Open-source local trainer"], objective: "Make data quality and train/evaluation separation explicit.", code: "record Example(String id, String input, String expected) {}\nstatic void validate(List<Example> train, Set<String> evalIds) {\n  var ids = new HashSet<String>();\n  for (var e : train) if (!ids.add(e.id()) || evalIds.contains(e.id()))\n    throw new IllegalArgumentException(\"duplicate or leakage\");\n}", successCriteria: ["No train/evaluation overlap.", "Base and adapted models run the same tests."] },
    breakExercise: { faults: ["Copy evaluation cases into training.", "Remove safety examples."], observe: ["Inflated score", "Safety regression"], recovery: "Repair and version data, then promote only when all gates pass." },
    explanation: { prompt: "Explain when fine-tuning is stronger than prompting or RAG.", evidenceCriteria: ["Parameter change", "Behaviour versus knowledge", "Rollback"] },
    awsMap: [{ invariant: "Adapt supported models", implementation: "Amazon Bedrock model customisation", why: "Use supported methods for a measured behaviour goal." }, { invariant: "Own custom training", implementation: "Amazon SageMaker AI", why: "Control data, training, artifacts, and hosting." }],
    examLens: "Fine-tuning changes behaviour; RAG supplies current context; prompting gives instructions.",
    questions: [
      { id: "aif-finetune-change", prompt: "What does fine-tuning change?", options: ["Model parameters", "Source docs per request", "TLS certificates", "IAM groups"], correctAnswer: "Model parameters", explanation: "Fine-tuning optimises weights.", reviewLabel: "Fine-tuning" },
      { id: "aif-finetune-choice", prompt: "Which need favours RAG?", options: ["Changing knowledge requiring citations", "Stable tone", "Terminology", "Repeated format"], correctAnswer: "Changing knowledge requiring citations", explanation: "Retrieval supplies current evidence.", reviewLabel: "Adaptation choice" },
    ],
  }),
  capabilityUnit({
    id: "model-evaluation",
    domainId: "foundation-models",
    sequence: 12,
    difficulty: "Hard",
    title: "Model evaluation",
    subtitle: "Turn quality, safety, latency, and cost into release evidence.",
    principle: "Evaluation tests a model-plus-application under representative conditions, not one benchmark.",
    goal: "Design offline, human, operational, subgroup, and adversarial gates.",
    concepts: ["evaluation set", "baseline", "human review", "drift"],
    problem: "A model wins a public benchmark but gives worse grounded answers to learners.",
    mechanism: "Versioned cases sample real tasks and failures. Automated metrics, rubrics, humans, latency, cost, and safety compare candidate and baseline before and after release.",
    decision: { useWhen: ["Evaluate every model, prompt, retrieval, and guardrail change using error-cost metrics."], avoidWhen: ["Do not reuse training cases as final evidence or hide dimensions in one average."], alternatives: ["Contract tests", "Shadow traffic", "Canary", "Human review"] },
    tradeOffs: ["Automated metrics scale and miss nuance.", "Human review adds nuance, cost, and variability."],
    prediction: { prompt: "Candidate is cheaper but fails citation accuracy. Promote it?", preferred: ["No—keep the release gate", "Cost does not override trust criteria."], alternative: ["Yes—cost is everything", "Unsupported answers become an unapproved trade-off."] },
    recallPrompts: ["Why keep untouched evaluation cases?", "Name four dimensions beyond accuracy."],
    reasoning: { prompt: "Design release gates for rare but severe safety failures.", strongAnswerIncludes: ["Adversarial cases", "Independent metric floors", "Rollback"] },
    build: { title: "Compare candidate and baseline in Java", stack: ["Plain Java", "JUnit optional"], objective: "Fail promotion on explicit criteria.", code: "record Score(double quality, long latencyMs, double cost) {}\nstatic boolean passes(Score c, Score b) {\n  return c.quality() >= 0.90 && c.quality() >= b.quality() - 0.01\n      && c.latencyMs() <= 1500;\n}", successCriteria: ["Both versions use identical cases.", "Any required failure blocks promotion."] },
    breakExercise: { faults: ["Test easy cases only.", "Average away one severe failure."], observe: ["Selection bias", "Hidden tail risk"], recovery: "Version data and rubrics, report dimensions separately, and inspect severe failures." },
    explanation: { prompt: "Explain why a benchmark does not prove application readiness.", evidenceCriteria: ["Application context", "Multiple dimensions", "Continuous evidence"] },
    awsMap: [{ invariant: "Evaluate foundation-model outputs", implementation: "Amazon Bedrock model evaluation", why: "Compare supported models and criteria." }, { invariant: "Analyse bias and drift", implementation: "SageMaker Clarify and Model Monitor", why: "Support custom ML lifecycle evidence." }],
    examLens: "Match methods and metrics to use case, error cost, and lifecycle stage.",
    questions: [
      { id: "aif-eval-set", prompt: "What makes an evaluation set useful?", options: ["Representative cases without training leakage", "Easy cases only", "Changing rubric", "Cost only"], correctAnswer: "Representative cases without training leakage", explanation: "Untouched cases estimate transfer.", reviewLabel: "Evaluation design" },
      { id: "aif-eval-release", prompt: "Quality rises but safety fails. What happens?", options: ["Block promotion", "Average and ship", "Delete safety tests", "Hide baseline"], correctAnswer: "Block promotion", explanation: "A safety floor remains independent.", reviewLabel: "Release gates" },
    ],
  }),
  capabilityUnit({
    id: "responsible-ai-principles",
    domainId: "responsible-ai",
    sequence: 13,
    difficulty: "Hard",
    title: "Responsible AI",
    subtitle: "Design fairness, transparency, robustness, privacy, and accountability.",
    principle: "Responsible AI is an organisational lifecycle practice, not a property a model owns.",
    goal: "Identify affected groups, test outcomes, document use, and retain accountable humans.",
    concepts: ["fairness", "bias", "transparency", "explainability", "oversight"],
    problem: "An access model scores well overall but one group has twice the false-positive rate.",
    mechanism: "Risk enters through samples, labels, features, objectives, thresholds, interfaces, and use. Teams define use, measure groups, document limits, provide review, and monitor.",
    decision: { useWhen: ["Apply proportional review to every AI system and human oversight to high-impact decisions."], avoidWhen: ["Do not claim aggregate accuracy proves fairness or explanation proves correctness."], alternatives: ["Deterministic policy", "Advisory output", "Human decision", "No automation"] },
    tradeOffs: ["Fairness definitions can conflict.", "Human review adds accountability and possible human bias."],
    prediction: { prompt: "Subgroup error differs materially. What next?", preferred: ["Pause automation and investigate", "Review preserves remedy while the system is repaired."], alternative: ["Ship on aggregate accuracy", "Concentrated harm stays hidden."] },
    recallPrompts: ["Where can bias enter?", "Why can fairness definitions conflict?"],
    reasoning: { prompt: "Set release conditions for an advisory access recommendation.", strongAnswerIncludes: ["Intended use", "Subgroup thresholds", "Appeal and monitoring"] },
    build: { title: "Measure subgroup false positives", stack: ["Plain Java"], objective: "Expose unequal error hidden by an aggregate.", code: "record Outcome(String group, boolean actual, boolean predicted) {}\nstatic double fpr(List<Outcome> rows, String group) {\n  var n = rows.stream().filter(r -> r.group().equals(group) && !r.actual()).toList();\n  long fp = n.stream().filter(Outcome::predicted).count();\n  return n.isEmpty() ? 0 : (double) fp / n.size();\n}", successCriteria: ["Aggregate and subgroup results are shown.", "Small samples are flagged."] },
    breakExercise: { faults: ["Remove a group from tests.", "Automate without appeal."], observe: ["Coverage blind spot", "Missing accountability"], recovery: "Repair representation, reassess thresholds, document limits, and preserve appeal." },
    explanation: { prompt: "Explain responsible AI as a lifecycle with an accountable owner.", evidenceCriteria: ["Affected groups", "Lifecycle evidence", "Remedy"] },
    awsMap: [{ invariant: "Measure bias and explain behaviour", implementation: "SageMaker Clarify", why: "Support bias and explainability analysis." }, { invariant: "Document and monitor use", implementation: "SageMaker Model Cards and Model Monitor", why: "Retain lifecycle evidence." }],
    examLens: "Keep fairness, explainability, privacy, safety, robustness, and oversight distinct.",
    questions: [
      { id: "aif-responsible-bias", prompt: "Where can bias enter?", options: ["Across data, objectives, deployment, and use", "Only UI colour", "Only inference", "Nowhere with accuracy"], correctAnswer: "Across data, objectives, deployment, and use", explanation: "Risk spans the lifecycle.", reviewLabel: "Bias" },
      { id: "aif-responsible-human", prompt: "Why retain human review?", options: ["Challenge errors and preserve remedy", "Humans have no bias", "Avoid tests", "Make model deterministic"], correctAnswer: "Challenge errors and preserve remedy", explanation: "Oversight adds accountability.", reviewLabel: "Human oversight" },
    ],
  }),
  capabilityUnit({
    id: "guardrails",
    domainId: "responsible-ai",
    sequence: 14,
    difficulty: "Hard",
    title: "Guardrails",
    subtitle: "Layer input, output, tool, and escalation policies.",
    principle: "Guardrails reduce defined risks; they neither make models inherently safe nor replace authorization.",
    goal: "Place deterministic and model-assisted controls at correct layers.",
    concepts: ["input filter", "output filter", "topic policy", "PII", "tool permission"],
    problem: "An assistant may leak records, follow injected text, or call a powerful tool.",
    mechanism: "Input controls filter requests; data controls scope context; tool controls allow effects; output controls validate; monitoring and escalation handle misses.",
    decision: { useWhen: ["Use layers for safety, privacy, or policy and test bypass and overblocking."], avoidWhen: ["Do not use text filters as authorization or assume one guardrail covers all policy."], alternatives: ["Remove feature", "Deterministic flow", "Human moderation", "Read-only tools"] },
    tradeOffs: ["Strict filters block harm and valid requests.", "Classifiers add nuance and latency."],
    prediction: { prompt: "A model proposes a refund. What moves money?", preferred: ["Deterministic policy and authorization", "Trusted code enforces identity, amount, and rules."], alternative: ["A careful prompt", "Probabilistic text becomes a financial control."] },
    recallPrompts: ["Name four guardrail layers.", "Define false positive and false negative."],
    reasoning: { prompt: "Design controls for search-only notes with no account changes.", strongAnswerIncludes: ["Read-only tool", "Input/output policy", "Logging and escalation"] },
    build: { title: "Compose Java policy checks", stack: ["Plain Java"], objective: "Keep tool permission explicit.", code: "static final Set<String> ALLOWED = Set.of(\"searchCourseNotes\");\nstatic void authorise(String tool) {\n  if (!ALLOWED.contains(tool)) throw new SecurityException(\"not allowed\");\n}\nstatic String guard(String out) {\n  return out.matches(\".*\\\\b\\\\d{3}-\\\\d{2}-\\\\d{4}\\\\b.*\") ? \"withheld\" : out;\n}", successCriteria: ["Disallowed tools fail closed.", "Tests cover bypass and overblocking."] },
    breakExercise: { faults: ["Obfuscate sensitive text.", "Request a tool indirectly."], observe: ["Pattern bypass", "Intent versus string gap"], recovery: "Layer permissions, classifiers, schema checks, adversarial tests, and escalation." },
    explanation: { prompt: "Explain what guardrails reduce, cannot guarantee, and where authorization belongs.", evidenceCriteria: ["Layers", "Limits", "Authorization"] },
    awsMap: [{ invariant: "Apply model-interaction policy", implementation: "Guardrails for Amazon Bedrock", why: "Enforce configured content and sensitive-data controls." }, { invariant: "Constrain effects and data", implementation: "IAM and application authorization", why: "Permissions decide what workloads may do." }],
    examLens: "Guardrails complement IAM, encryption, minimisation, evaluation, and oversight.",
    questions: [
      { id: "aif-guardrail-role", prompt: "What is a guardrail's role?", options: ["Reduce defined risks as one layer", "Guarantee safety", "Replace IAM", "Train models"], correctAnswer: "Reduce defined risks as one layer", explanation: "Guardrails retain scope and failure limits.", reviewLabel: "Guardrails" },
      { id: "aif-guardrail-tool", prompt: "What authorizes a financial action?", options: ["Deterministic policy and permissions", "Model confidence", "Long prompt", "Similarity"], correctAnswer: "Deterministic policy and permissions", explanation: "Trusted code controls effects.", reviewLabel: "Tool authorization" },
    ],
  }),
  capabilityUnit({
    id: "ai-security",
    domainId: "ai-security",
    sequence: 15,
    difficulty: "Hard",
    title: "AI security",
    subtitle: "Protect identity, data, transport, models, prompts, tools, and logs.",
    principle: "AI extends application security; model risks add layers without moving TLS or authorization.",
    goal: "Place IAM, encryption, TLS, mTLS, validation, minimisation, and audit correctly.",
    concepts: ["least privilege", "KMS", "TLS", "mTLS", "prompt injection", "audit"],
    problem: "A private AI workflow crosses networks, reads learner data, invokes a model, and calls tools.",
    mechanism: "IAM authorizes. Encryption protects storage. TLS encrypts transport and authenticates servers; mTLS adds client-certificate authentication. Application controls scope data and effects.",
    decision: { useWhen: ["Use TLS on sensitive hops and mTLS when both services need certificate identity; keep authorization independent."], avoidWhen: ["Do not use mTLS as user/action authorization or put unapproved data in prompts."], alternatives: ["Private network", "Workload tokens", "Signed requests", "Service mesh identity"] },
    tradeOffs: ["mTLS adds rotation and revocation.", "Private networks do not encrypt or authorize alone.", "Logs can capture sensitive data."],
    prediction: { prompt: "Two services need encrypted transport and mutual workload identity. What fits?", preferred: ["mTLS plus authorization", "Both peers authenticate during TLS while policy controls actions."], alternative: ["Caller name in prompt", "Text is mistaken for cryptographic identity."] },
    recallPrompts: ["What does TLS provide?", "What does mTLS add and not add?"],
    reasoning: { prompt: "Place controls across browser, API, model, learner data, tools, and logs.", strongAnswerIncludes: ["Transport versus application", "Least privilege", "Secret-safe logs"] },
    build: { title: "Create a Java mTLS client", stack: ["Java HttpClient", "PKCS#12", "Trust store"], objective: "Demonstrate mutual authentication at transport.", code: "char[] password = System.getenv(\"MTLS_STORE_PASSWORD\").toCharArray();\nvar keys = KeyStore.getInstance(\"PKCS12\");\ntry (var in = Files.newInputStream(Path.of(System.getenv(\"MTLS_KEYSTORE\")))) { keys.load(in, password); }\nvar kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());\nkmf.init(keys, password);\nvar ssl = SSLContext.getInstance(\"TLS\");\nssl.init(kmf.getKeyManagers(), null, new SecureRandom());\nvar client = HttpClient.newBuilder().sslContext(ssl).build();", successCriteria: ["Server is validated.", "Unapproved clients fail.", "Authorization still checks actions."] },
    breakExercise: { faults: ["Expire client certificate.", "Use untrusted CA.", "Log store password."], observe: ["Handshake failure", "Trust failure", "Secret exposure"], recovery: "Automate rotation and revocation, fail closed, redact, and retain authorization." },
    explanation: { prompt: "Explain TLS/mTLS at transport and separate authorization and data controls.", evidenceCriteria: ["Layer placement", "Mutual identity", "Certificate lifecycle"] },
    awsMap: [{ invariant: "Manage certificates", implementation: "AWS Certificate Manager and AWS Private CA", why: "Support public and private certificate lifecycle." }, { invariant: "Mutually authenticate API transport", implementation: "Amazon API Gateway mTLS where appropriate", why: "Authenticate client certificates at the API boundary." }, { invariant: "Authorize model and data", implementation: "IAM, KMS, and scoped Bedrock permissions", why: "Transport identity does not grant actions." }],
    examLens: "TLS/mTLS is transport, IAM is authorization, KMS supports encryption, and guardrails govern model interaction.",
    questions: [
      { id: "aif-security-mtls", prompt: "What does mTLS add?", options: ["Client certificate authentication in TLS", "Business authorization", "Factuality", "Vector encryption"], correctAnswer: "Client certificate authentication in TLS", explanation: "mTLS authenticates both transport peers.", reviewLabel: "mTLS" },
      { id: "aif-security-layer", prompt: "What controls which Bedrock model a workload invokes?", options: ["Least-privilege IAM", "Similarity", "Certificate subject alone", "Prompt text"], correctAnswer: "Least-privilege IAM", explanation: "IAM authorizes AWS API actions.", reviewLabel: "Least privilege" },
    ],
  }),
  capabilityUnit({
    id: "ai-governance",
    domainId: "ai-security",
    sequence: 16,
    difficulty: "Hard",
    title: "AI governance",
    subtitle: "Make ownership, policy, versions, evidence, and exceptions operational.",
    principle: "Governance makes AI decisions attributable, reviewable, reproducible, and changeable.",
    goal: "Define inventory, owners, approvals, versions, evaluation, monitoring, incidents, and retirement.",
    concepts: ["governance", "inventory", "approval", "auditability", "lineage"],
    problem: "An auditor asks which model and prompt answered, who approved them, what data was allowed, and what evaluation passed.",
    mechanism: "Governance links use case, owner, risk, lineage, model, prompt, evaluation, deployment, access, exception, incident, and retirement. Preventive controls block; detective controls reveal.",
    decision: { useWhen: ["Govern every production use case with depth proportional to risk and automate evidence."], avoidWhen: ["Do not rely on unenforced documents or retain raw prompts without purpose."], alternatives: ["Do not deploy", "Manual pilot", "Deterministic workflow"] },
    tradeOffs: ["Controls can slow low-risk experiments without tiers.", "Audit data aids response and adds privacy duties."],
    prediction: { prompt: "A developer changes the production model ID. What is required?", preferred: ["Version, evaluation, approval, rollback", "The release is attributable and reversible."], alternative: ["Trust memory", "No evidence connects change to outcome."] },
    recallPrompts: ["What makes output reproducible?", "Preventive versus detective control?"],
    reasoning: { prompt: "Contrast governance for a summariser and a high-impact recommendation.", strongAnswerIncludes: ["Risk and owner", "Proportional approval", "Monitoring and retirement"] },
    build: { title: "Emit a Java AI decision record", stack: ["Plain Java", "Append-only audit sink"], objective: "Capture reproducibility without unnecessary sensitive content.", code: "record AiDecisionRecord(UUID requestId, String useCaseId,\n    String modelVersion, String promptVersion, List<String> sourceIds,\n    String evaluationRelease, Instant occurredAt) {}\nvar record = new AiDecisionRecord(UUID.randomUUID(), \"course-assistant\",\n    \"model-7\", \"prompt-12\", List.of(\"policy-2026-08\"), \"eval-44\", Instant.now());", successCriteria: ["Output links to model, prompt, sources, and evaluation.", "No secret or unnecessary learner data is stored."] },
    breakExercise: { faults: ["Remove prompt version.", "Allow unapproved model.", "Store every raw prompt forever."], observe: ["Lost reproducibility", "Policy bypass", "Privacy risk"], recovery: "Validate evidence, enforce approved versions, and minimise audit data." },
    explanation: { prompt: "Explain governance as a control loop from proposal to retirement.", evidenceCriteria: ["Ownership and risk", "Evidence and enforcement", "Incident path"] },
    awsMap: [{ invariant: "Record AWS API activity", implementation: "AWS CloudTrail", why: "Investigate governed use and change." }, { invariant: "Apply organisation permission guardrails", implementation: "AWS Organizations service control policies", why: "Constrain actions without granting them." }, { invariant: "Assess configuration and evidence", implementation: "AWS Config and AWS Audit Manager", why: "Support detective controls and evidence." }],
    examLens: "Separate governance, preventive control, detective evidence, compliance, and runtime security.",
    questions: [
      { id: "aif-governance-evidence", prompt: "What best supports output reproducibility?", options: ["Model, prompt, source, config, and evaluation versions", "Final prose only", "Developer only", "Invoice only"], correctAnswer: "Model, prompt, source, config, and evaluation versions", explanation: "Versioned artifacts connect output to context.", reviewLabel: "Governance evidence" },
      { id: "aif-governance-control", prompt: "What is a preventive control?", options: ["Block unapproved deployment", "Review incident later", "Read logs", "Calculate cosine"], correctAnswer: "Block unapproved deployment", explanation: "Preventive controls stop non-compliant change.", reviewLabel: "Governance controls" },
    ],
  }),
]

export function getAifC01Capability(capabilityId: string): LearningUnit | null {
  return aifC01CapabilityUnits.find((unit) => unit.id === capabilityId) ?? null
}

export function getAifC01CapabilitiesForDomain(domainId: string): LearningUnit[] {
  return aifC01CapabilityUnits.filter((unit) => unit.certification?.domainId === domainId)
}
